allowBuilds:
  browser-tabs-lock: true

pmOnFail: error
packageManagerStrictVersion: true
minimumReleaseAge: 10080 # 7 days in minutes
minimumReleaseAgeStrict: true
trustPolicy: no-downgrade
blockExoticSubdeps: true
strictDepBuilds: true
